In [1]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [3]:
save_path = "/Users/deveshshah/Documents/Programming/Out_Of_Distribution_Exploration/dataset/dtd/"

In [4]:
transform = transforms.Compose([transforms.ToTensor()])

In [5]:
# Stanford Cars - test set
dtd = datasets.DTD(root=save_path, split="test", download=True, transform=transform)

100%|██████████| 625M/625M [04:08<00:00, 2.51MB/s]

In [1]:
import os
import pandas as pd

In [2]:
all_images = os.listdir("/Users/deveshshah/Documents/Programming/Out_Of_Distribution_Exploration/dataset/imagenet-o/images_resized")

In [3]:
len(all_images)

2000

In [4]:
all_images = [x for x in all_images if x.endswith(".jpg")]

In [5]:
len(all_images)

2000

In [6]:
df = pd.DataFrame(all_images, columns=["image_path"])
df["stage"] = "train"
df["label"] = "ood_wild"
df["id"] = "imagenet-o_" + df.index.astype(str)

In [7]:
df = df[["id", "image_path", "label", "stage"]]

In [8]:
df.head()

,id,image_path,label,stage
0,imagenet-o_0,headset_0.9965918.jpg,ood_wild,train
1,imagenet-o_1,quadrate_0.99998045.jpg,ood_wild,train
2,imagenet-o_2,computerized_axial_tomography_scanner_CAT_scan...,ood_wild,train
3,imagenet-o_3,sandbag_0.9993542.jpg,ood_wild,train
4,imagenet-o_4,Sheetrock_0.9742838.jpg,ood_wild,train

In [10]:
# randomly set 20% of data to val
from random import random, sample
all_ids = df["id"].tolist()
val_ids = set(sample(all_ids, int(0.2 * len(all_ids))))
df["stage"] = df["id"].apply(lambda x: "val" if x in val_ids else "train")

In [11]:
df.head()

,id,image_path,label,stage
0,imagenet-o_0,headset_0.9965918.jpg,ood_wild,train
1,imagenet-o_1,quadrate_0.99998045.jpg,ood_wild,train
2,imagenet-o_2,computerized_axial_tomography_scanner_CAT_scan...,ood_wild,train
3,imagenet-o_3,sandbag_0.9993542.jpg,ood_wild,train
4,imagenet-o_4,Sheetrock_0.9742838.jpg,ood_wild,train

In [14]:
df["id"].nunique()

2000

In [15]:
len(df), df["id"].nunique()

(2000, 2000)

In [16]:
df.to_csv("/Users/deveshshah/Documents/Programming/Out_Of_Distribution_Exploration/dataset/imagenet-o/dataset.csv", index=False)